### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/brackets-plugin-exclusions#1]
Hello @bemjb!
My name is Fil and I’m from Adobe’s Open Source Office. Funny, I think we're set to speak this week about internal Adobe dev stuff anyways 😄 small world.

I'll cut to the point: I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project? Or even remove it altogether?

Thanks for any info.

-Fil

**Comment by bemjb** [comment]
Hey @filmaj! I certainly haven't touched this project in the past 6 years. It is quite possible that it doesn't work with the current version of Brackets, and it is also likely that no one knows what "CSS Exclusions" are since the current spec is just CSS Shapes. So I can't come up with any reasons why it wouldn't be ok to archive it. I'm not a big fan of deleting it entirely unless there's a bunch of work that needs to be done to archive it that we wouldn't have to do if we deleted it.

**Comment by filmaj** [comment]
You bet, archiving sounds right to me too. I'll send a PR to update the README with the maintenance state and get you to review it if that's OK? Once we've done that I can do the archiving - it's just the flip of a switch.

**Comment by filmaj** [comment]
Thanks for merging the PR!

I will now archive this repo, RIP. 🌹😞 🌹
